packages:
  - httpd
  - httpd-tools
  - httpd-manual
  - crypto-utils
  - mod_fcgid
  - mod_ssl
  - perl-Newt
  - chrony

unnecessary_services:
  - postfix
  - telnet
unnecessary_software:
  - tcpdump
  - nmap-ncat
  - wpa_supplicant
