packages:
  - httpd
  - httpd-tools
  - httpd-manual
  - crypto-utils
  - mod_fcgid
  - mod_ssl
  - perl-Newt
  - chrony
  - python3
  - python3-pip

pip:
  - cryptography

unnecessary_services:
  - postfix
  - telnet
unnecessary_software:
  - tcpdump
  - nmap-ncat
  - wpa_supplicant

certificate_passphrase: "{{lookup('aws_secret', '{{ ssl_secret_name }}')}}"
