---
- hosts: localhost
  module_defaults:
    group/aws:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'

  roles:
    - deploy_infra
    - configure_vm
    # - deploy_site
  
  # tasks:
  # - name: Print Hello World
  #   debug:
