- name: Get packages
  include_vars: "../vars/vars.yml"

- name: Enable EPEL repo on AL2
  command: "{{ item }}"
  loop:
    - amazon-linux-extras enable epel
    - yum clean metadata
  become: true
  register: output
  changed_when: "output.stderr | length == 0"

- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  become: true
