- name: Get packages
  include_vars: "../vars/vars.yml"

- name: Update packages to latest
  package:
    name: "*"
    state: latest
  tags:
    - skip_ansible_lint # Doesn't like state: latest
  become: true

- name: Install EPEL repo on AL2
  command: "{{ item }}"
  loop:
    - amazon-linux-extras install epel
  become: true
  register: output
  changed_when: "'Nothing to do' not in output.stdout"

- name: Deploy Hardened SSH server config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  become: true
  notify: "Reload SSH"

- name: Flush handlers
  meta: flush_handlers

- name: Remove problematic packages
  package:
    name: "{{ unnecessary_software }}"
    state: absent
  become: true

- name: Disable services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ unnecessary_services }}"
  ignore_errors: true # Used in case service doesn't exist on system
  become: true
  tags:
    - skip_ansible_lint # Doesn't like ignore_errors

- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  become: true
