- name: Create path
  file:
    path: "{{ playbook_dir ~ '/aws/' }}"
    state: directory
    mode: u+rwx
  args:
    creates: "{{ playbook_dir ~ '/aws/' }}"
  listen: "Write keypair to file"

- name: Write keypair value to file
  copy:
    content: "{{ keypair.key.private_key }}"
    dest: "{{ playbook_dir ~ '/aws/keypair.pem' }}"
    mode: "400"
  listen: "Write keypair to file"

- name: Update ansible.cfg
  lineinfile:
    backup: true
    insertafter: "\\[defaults]"
    state: present
    line: "{{ item }}"
    path: "{{ playbook_dir ~ '/ansible.cfg' }}"
  loop:
    - private_key_file="/aws/keypair.pem"
    # - remote_user="ec2-user" # Unsure if this is still needed
  listen: "Write keypair to file"
