- name: Start service ssh, if not started
  ansible.builtin.service:
    name: sshd
    state: reloaded
    enabled: true
  become: true
  listen: "Reload SSH"

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
  become: true
  listen: "Restart httpd"